### ISSUE TITLE
"login" doesn't seem functional?

### ISSUE THREAD

**Issue by justinclift** [datopian/data-cli#147]
Just downloaded `datahub-linux`, made it executable, then tried to figure out what to do. :smile:

The `login` option sounds like it might be what I want, but that's just throwing an error:

```
$ ./datahub-linux login
? Login with... (Use arrow keys)
❯ Github
```

I then just press Enter, as it's the only option, which throws the error:

```
? Login with...Github
> Opening browser and waiting for you to authenticate online
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn /snapshot/datahub-cli/node_modules/opn/xdg-open ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

It's mentioning it's opening a browser to Auth with.  No browser window is showing up though, and that error occurs immediately (likely related).

Any ideas? :smile:

**Comment by anuveyatsu** [comment]
Hi, @justinclift thanks for reporting!
Seems like this issue was fixed in the upstream library (https://github.com/zeit/pkg/issues/207) and we will check/update if so.

**Comment by justinclift** [comment]
@anuveyatsu Thanks. :smile:

**Comment by offray** [comment]
We have downloaded version 0.4.1 and the login problem is still present. The documentation on [OPN#207](https://github.com/zeit/pkg/issues/207) is not clear enough about how to get the updated version. I don't know if this bug fix is only enabled in npm install because npm is not working for us.

**Comment by Mikanebu** [comment]
@offray thanks for raising this again and we'll investigate.

**Comment by Mikanebu** [comment]
@offray it was fixed in `pkg` https://github.com/zeit/pkg/issues/207 27 days ago, but we are using `"pkg": "^4.2.2"` which released on August 6. There is still no new release since it has been fixed. I will keep you updated

**Comment by Mikanebu** [comment]
@justinclift @offray updated with new release of `pkg@4.2.5`, original lunix login issue fixed, but there is now different error related to location of executable `xdg-open`. So, temporary fix would be to copy across executable into `/usr/local/bin/xdg-open`, because `pkg` library looks for this location `/usr/bin/xdg-open`. There is an open issue in https://github.com/zeit/pkg/issues/229. Once it will be fixed, I will update you. Also, I will update docs as well, it can be found here http://datahub.io/docs/getting-started/installing-data
