### ISSUE TITLE
auto update not working

### ISSUE THREAD

**Issue by Stephen-Gates** [datopian/data-cli#268]
<img width="319" alt="screenshot 2018-02-08 21 21 33" src="https://user-images.githubusercontent.com/9379524/35971191-cd7e1166-0d18-11e8-813f-723ea93e9da6.png">

Tried a few times but no luck

**Comment by anuveyatsu** [comment]
@Stephen-Gates this is because we're compressing all assets and now they've got `.gz` extension, which is confusing the desktop app when looking for the asset https://github.com/datahq/data-desktop/blob/master/main/utils/binary.js#L259

I'll fix that ASAP in the next 24h and you won't need to re-install anything.

**Comment by anuveyatsu** [comment]
@Stephen-Gates can you please try again now - should be fixed. Please, reopen the issue if still broken.

**Comment by Stephen-Gates** [comment]
Fixed 👍
